alias fa='make && ./bin/debug/factorio'
alias fd='make && lldb ./bin/debug/factorio'
alias fp='make mode=prod && ./bin/prod/factorio'
alias fsp='make SAVING_TAGS=1 mode=prod && ./bin/prod/factorio'
alias fk='pkill -9 factorio'
alias lk='pkill -9 lldb'
alias cfp='cd ~/Code/Factorio/Primary'
alias cfs='cd ~/Code/Factorio/Secondary'
alias cft='cd ~/Code/Factorio/Tertiary'
